# @file      .gitlab-ci.yml
# @author    Ignacio Vizzo     [ivizzo@uni-bonn.de]
#
# Copyright (c) 2020 Ignacio Vizzo, all rights reserved
image: prbonn/ros:noetic
stages:
  - validate
  - update

check_models:
  stage: validate
  script:
    - echo "TODO!!! Add CI for hardware and URDF verification models"

include:
  - project: 'ipb-team/robots/ipb-car/meta-workspace'
    ref: master
    file: '.templates/.gitlab-ci-submodule-update.yml'
